### ISSUE TITLE
Hail kills itself when activating NixOS profile

### ISSUE THREAD

**Issue by phile314-fh** [TaktInc/hail#10]
We are using Hail to deploy NixOS configurations built by Hydra to our machines. The Hydra Job builds the NixOS configuration and just produces a small wrapper script at $out/bin/activate as expected by hail:

    #!/nix/store/6vk...9h-bash-4.4-p12/bin/bash
    # call NixOS activation script
    /nix/store/m9...mh-nixos-system-web-ci-17.09pre-git/bin/switch-to-configuration switch

We are using a small systemd service to run Hail. In general, this works quite well. However, we have run into a problem when the Hail service itself has been updated, e.g. through a new NixOS channel version. In that case, the NixOS activation script will try to restart the Hail service which seems to kill the activation script itself:

Hail -> calls ../bin/activate -> calls switch-configuration -> restarts Hail

For now, we have just disabled restarting Hail using the ``restartIfChanged`` NixOS service option. We are not entirely sure yet if that fixes it. In any case, that's not terribly nice to do, as now we are never updating hail anymore. Do you have any suggestion how we can restart Hail without killing the activation script?

**Comment by shlevy** [comment]
You probably want to use something like https://github.com/TaktInc/hail/blob/92c83fb99ef6796271a760edbc9ee6b8c757da5e/hail-systemd-bootstrap.nix#L114-L119 for your activation script. Once you get it working I'd love to see an upstream NixOS module!

**Comment by phile314-fh** [comment]
Thanks for the tip, worked beautifully 👍 

I had to pass on PATH and LOCALE_ARCHIVE, as else switch-to-configuration couldn't find ``systemctl`` nor the perl locales:

    #!${pkgs.bash}/bin/bash
    # We use systemd-run because the program calling this
    # script may be one of the services being updated.
    exec -a systemd-run ${pkgs.systemd}/bin/systemd-run \
        --description "Hail: Activate new configuration" \
        -E PATH=$PATH \
        -E LOCALE_ARCHIVE=$LOCALE_ARCHIVE \
        ${machineCfg}/bin/switch-to-configuration switch

I will make a PR for the NixOS module later this week.
